# yaml 配置
services:
  hotel_demo:
    image: hotel_demo:${version}
    container_name: hotel_demo
    build:
      context: ..
      dockerfile: ./docker/ubuntu/Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    volumes:
      - ${VOLUME_PATH}/mongo/data:/data/db
      - ${VOLUME_PATH}/backend/logs:/www/backend/logs
    ports:
      - "${MY_MONGODB_PORT}:27017"
      - "${MY_SERVER_PORT}:4000"
      - "${MY_WEB_PORT}:80"
    stdin_open: true  # 允许标准输入保持打开状态（适用于交互式会话）
    tty: true         # 分配一个伪终端，让你可以保持连接
    networks:
      - hotel_network

networks:
  hotel_network:
    driver: bridge